# Generated by Django 5.1.2 on 2024-11-23 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_carrito_estado_producto_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoproductos',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
